# config/packages/easy_admin.yaml
easy_admin:
  design:
    menu:
      - { entity: "User", label: "Utilisateurs" }

  entities:
    User:
      class: App\Entity\User
      login_name: email
      list:
        - email
        - { property: "roles", label: "Rôles" }
      form:
        fields:
          - email
          - { property: "password", type: "text" }
          - roles
  
