vich_uploader:
  db_driver: orm
  mappings:
    teams:
      uri_prefix: "%logo%"
      upload_destination: "%kernel.project_dir%/public/uploads/team_logos"
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: Vich\UploaderBundle\Naming\UniqidNamer
